[package]
name = "qpatcher"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.1.4", features = ["derive"] }
json = "0.12.4"
nix = { version = "0.26.2", features = ["fs"]}
reqwest = "0.11.14"
