name: Test and build Quartet

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - uses: pnpm/action-setup@v2
              with:
                  version: ^7

            - uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: "pnpm"

            - name: Install project
              run: pnpm install

            - name: Lint project
              run: pnpm lint

            - name: Check for typescript errors
              run: pnpm tsc --noEmit

    build:
        if: ${{ github.event == 'push' }}
        needs: test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - uses: pnpm/action-setup@v2
              with:
                  version: ^7

            - uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: "pnpm"

            - name: Install project
              run: pnpm install

            - name: Build all versions
              run: pnpm build --web

            - name: Upload artifacts
              uses: actions/upload-artifact@v3
              with:
                  path: dist/
