name: Test Quartet

on:
    push:
        branches-ignore:
            - main
    pull_request:
        branches:
            - main

jobs:
    test-node:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3

          - uses: pnpm/action-setup@v2
            with:
                version: ^7

          - uses: actions/setup-node@v3
            with:
                node-version: 18
                cache: "pnpm"

          - name: Install project
            run: pnpm install

          - name: Lint using ESLint
            run: pnpm lint

          - name: Check for TypeScript errors
            run: pnpm tsc --noEmit

          - name: Build everything
            run: pnpm build --web

    test-d:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - uses: dlang-community/setup-dlang@v1
              with:
                  compiler: ldc-latest

            - name: Build qpatcher
              run: dub build --root=patcher -b release
